// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spipe.proto

package spipe.pb;

public final class Spipe {
  private Spipe() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProposeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:spipe.pb.Propose)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes rand = 1;</code>
     * @return Whether the rand field is set.
     */
    boolean hasRand();
    /**
     * <code>optional bytes rand = 1;</code>
     * @return The rand.
     */
    com.google.protobuf.ByteString getRand();

    /**
     * <code>optional bytes pubkey = 2;</code>
     * @return Whether the pubkey field is set.
     */
    boolean hasPubkey();
    /**
     * <code>optional bytes pubkey = 2;</code>
     * @return The pubkey.
     */
    com.google.protobuf.ByteString getPubkey();

    /**
     * <code>optional string exchanges = 3;</code>
     * @return Whether the exchanges field is set.
     */
    boolean hasExchanges();
    /**
     * <code>optional string exchanges = 3;</code>
     * @return The exchanges.
     */
    java.lang.String getExchanges();
    /**
     * <code>optional string exchanges = 3;</code>
     * @return The bytes for exchanges.
     */
    com.google.protobuf.ByteString
        getExchangesBytes();

    /**
     * <code>optional string ciphers = 4;</code>
     * @return Whether the ciphers field is set.
     */
    boolean hasCiphers();
    /**
     * <code>optional string ciphers = 4;</code>
     * @return The ciphers.
     */
    java.lang.String getCiphers();
    /**
     * <code>optional string ciphers = 4;</code>
     * @return The bytes for ciphers.
     */
    com.google.protobuf.ByteString
        getCiphersBytes();

    /**
     * <code>optional string hashes = 5;</code>
     * @return Whether the hashes field is set.
     */
    boolean hasHashes();
    /**
     * <code>optional string hashes = 5;</code>
     * @return The hashes.
     */
    java.lang.String getHashes();
    /**
     * <code>optional string hashes = 5;</code>
     * @return The bytes for hashes.
     */
    com.google.protobuf.ByteString
        getHashesBytes();
  }
  /**
   * Protobuf type {@code spipe.pb.Propose}
   */
  public static final class Propose extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:spipe.pb.Propose)
      ProposeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Propose.newBuilder() to construct.
    private Propose(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Propose() {
      rand_ = com.google.protobuf.ByteString.EMPTY;
      pubkey_ = com.google.protobuf.ByteString.EMPTY;
      exchanges_ = "";
      ciphers_ = "";
      hashes_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Propose();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Propose(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              rand_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              pubkey_ = input.readBytes();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              exchanges_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              ciphers_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              hashes_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return spipe.pb.Spipe.internal_static_spipe_pb_Propose_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return spipe.pb.Spipe.internal_static_spipe_pb_Propose_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              spipe.pb.Spipe.Propose.class, spipe.pb.Spipe.Propose.Builder.class);
    }

    private int bitField0_;
    public static final int RAND_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString rand_;
    /**
     * <code>optional bytes rand = 1;</code>
     * @return Whether the rand field is set.
     */
    @java.lang.Override
    public boolean hasRand() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes rand = 1;</code>
     * @return The rand.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRand() {
      return rand_;
    }

    public static final int PUBKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString pubkey_;
    /**
     * <code>optional bytes pubkey = 2;</code>
     * @return Whether the pubkey field is set.
     */
    @java.lang.Override
    public boolean hasPubkey() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes pubkey = 2;</code>
     * @return The pubkey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPubkey() {
      return pubkey_;
    }

    public static final int EXCHANGES_FIELD_NUMBER = 3;
    private volatile java.lang.Object exchanges_;
    /**
     * <code>optional string exchanges = 3;</code>
     * @return Whether the exchanges field is set.
     */
    @java.lang.Override
    public boolean hasExchanges() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string exchanges = 3;</code>
     * @return The exchanges.
     */
    @java.lang.Override
    public java.lang.String getExchanges() {
      java.lang.Object ref = exchanges_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exchanges_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string exchanges = 3;</code>
     * @return The bytes for exchanges.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExchangesBytes() {
      java.lang.Object ref = exchanges_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchanges_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CIPHERS_FIELD_NUMBER = 4;
    private volatile java.lang.Object ciphers_;
    /**
     * <code>optional string ciphers = 4;</code>
     * @return Whether the ciphers field is set.
     */
    @java.lang.Override
    public boolean hasCiphers() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string ciphers = 4;</code>
     * @return The ciphers.
     */
    @java.lang.Override
    public java.lang.String getCiphers() {
      java.lang.Object ref = ciphers_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ciphers_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ciphers = 4;</code>
     * @return The bytes for ciphers.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCiphersBytes() {
      java.lang.Object ref = ciphers_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ciphers_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HASHES_FIELD_NUMBER = 5;
    private volatile java.lang.Object hashes_;
    /**
     * <code>optional string hashes = 5;</code>
     * @return Whether the hashes field is set.
     */
    @java.lang.Override
    public boolean hasHashes() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string hashes = 5;</code>
     * @return The hashes.
     */
    @java.lang.Override
    public java.lang.String getHashes() {
      java.lang.Object ref = hashes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hashes_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string hashes = 5;</code>
     * @return The bytes for hashes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHashesBytes() {
      java.lang.Object ref = hashes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hashes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, rand_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, pubkey_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, exchanges_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ciphers_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, hashes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, rand_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, pubkey_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, exchanges_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ciphers_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, hashes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof spipe.pb.Spipe.Propose)) {
        return super.equals(obj);
      }
      spipe.pb.Spipe.Propose other = (spipe.pb.Spipe.Propose) obj;

      if (hasRand() != other.hasRand()) return false;
      if (hasRand()) {
        if (!getRand()
            .equals(other.getRand())) return false;
      }
      if (hasPubkey() != other.hasPubkey()) return false;
      if (hasPubkey()) {
        if (!getPubkey()
            .equals(other.getPubkey())) return false;
      }
      if (hasExchanges() != other.hasExchanges()) return false;
      if (hasExchanges()) {
        if (!getExchanges()
            .equals(other.getExchanges())) return false;
      }
      if (hasCiphers() != other.hasCiphers()) return false;
      if (hasCiphers()) {
        if (!getCiphers()
            .equals(other.getCiphers())) return false;
      }
      if (hasHashes() != other.hasHashes()) return false;
      if (hasHashes()) {
        if (!getHashes()
            .equals(other.getHashes())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRand()) {
        hash = (37 * hash) + RAND_FIELD_NUMBER;
        hash = (53 * hash) + getRand().hashCode();
      }
      if (hasPubkey()) {
        hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPubkey().hashCode();
      }
      if (hasExchanges()) {
        hash = (37 * hash) + EXCHANGES_FIELD_NUMBER;
        hash = (53 * hash) + getExchanges().hashCode();
      }
      if (hasCiphers()) {
        hash = (37 * hash) + CIPHERS_FIELD_NUMBER;
        hash = (53 * hash) + getCiphers().hashCode();
      }
      if (hasHashes()) {
        hash = (37 * hash) + HASHES_FIELD_NUMBER;
        hash = (53 * hash) + getHashes().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static spipe.pb.Spipe.Propose parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spipe.pb.Spipe.Propose parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spipe.pb.Spipe.Propose parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spipe.pb.Spipe.Propose parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spipe.pb.Spipe.Propose parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spipe.pb.Spipe.Propose parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spipe.pb.Spipe.Propose parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spipe.pb.Spipe.Propose parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static spipe.pb.Spipe.Propose parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static spipe.pb.Spipe.Propose parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static spipe.pb.Spipe.Propose parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spipe.pb.Spipe.Propose parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(spipe.pb.Spipe.Propose prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code spipe.pb.Propose}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:spipe.pb.Propose)
        spipe.pb.Spipe.ProposeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return spipe.pb.Spipe.internal_static_spipe_pb_Propose_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return spipe.pb.Spipe.internal_static_spipe_pb_Propose_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                spipe.pb.Spipe.Propose.class, spipe.pb.Spipe.Propose.Builder.class);
      }

      // Construct using spipe.pb.Spipe.Propose.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rand_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        pubkey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        exchanges_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        ciphers_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        hashes_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return spipe.pb.Spipe.internal_static_spipe_pb_Propose_descriptor;
      }

      @java.lang.Override
      public spipe.pb.Spipe.Propose getDefaultInstanceForType() {
        return spipe.pb.Spipe.Propose.getDefaultInstance();
      }

      @java.lang.Override
      public spipe.pb.Spipe.Propose build() {
        spipe.pb.Spipe.Propose result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public spipe.pb.Spipe.Propose buildPartial() {
        spipe.pb.Spipe.Propose result = new spipe.pb.Spipe.Propose(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rand_ = rand_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pubkey_ = pubkey_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.exchanges_ = exchanges_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ciphers_ = ciphers_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.hashes_ = hashes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof spipe.pb.Spipe.Propose) {
          return mergeFrom((spipe.pb.Spipe.Propose)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(spipe.pb.Spipe.Propose other) {
        if (other == spipe.pb.Spipe.Propose.getDefaultInstance()) return this;
        if (other.hasRand()) {
          setRand(other.getRand());
        }
        if (other.hasPubkey()) {
          setPubkey(other.getPubkey());
        }
        if (other.hasExchanges()) {
          bitField0_ |= 0x00000004;
          exchanges_ = other.exchanges_;
          onChanged();
        }
        if (other.hasCiphers()) {
          bitField0_ |= 0x00000008;
          ciphers_ = other.ciphers_;
          onChanged();
        }
        if (other.hasHashes()) {
          bitField0_ |= 0x00000010;
          hashes_ = other.hashes_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        spipe.pb.Spipe.Propose parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (spipe.pb.Spipe.Propose) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString rand_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes rand = 1;</code>
       * @return Whether the rand field is set.
       */
      @java.lang.Override
      public boolean hasRand() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes rand = 1;</code>
       * @return The rand.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRand() {
        return rand_;
      }
      /**
       * <code>optional bytes rand = 1;</code>
       * @param value The rand to set.
       * @return This builder for chaining.
       */
      public Builder setRand(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes rand = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rand_ = getDefaultInstance().getRand();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pubkey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes pubkey = 2;</code>
       * @return Whether the pubkey field is set.
       */
      @java.lang.Override
      public boolean hasPubkey() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes pubkey = 2;</code>
       * @return The pubkey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPubkey() {
        return pubkey_;
      }
      /**
       * <code>optional bytes pubkey = 2;</code>
       * @param value The pubkey to set.
       * @return This builder for chaining.
       */
      public Builder setPubkey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes pubkey = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPubkey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pubkey_ = getDefaultInstance().getPubkey();
        onChanged();
        return this;
      }

      private java.lang.Object exchanges_ = "";
      /**
       * <code>optional string exchanges = 3;</code>
       * @return Whether the exchanges field is set.
       */
      public boolean hasExchanges() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string exchanges = 3;</code>
       * @return The exchanges.
       */
      public java.lang.String getExchanges() {
        java.lang.Object ref = exchanges_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            exchanges_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string exchanges = 3;</code>
       * @return The bytes for exchanges.
       */
      public com.google.protobuf.ByteString
          getExchangesBytes() {
        java.lang.Object ref = exchanges_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchanges_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string exchanges = 3;</code>
       * @param value The exchanges to set.
       * @return This builder for chaining.
       */
      public Builder setExchanges(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        exchanges_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string exchanges = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExchanges() {
        bitField0_ = (bitField0_ & ~0x00000004);
        exchanges_ = getDefaultInstance().getExchanges();
        onChanged();
        return this;
      }
      /**
       * <code>optional string exchanges = 3;</code>
       * @param value The bytes for exchanges to set.
       * @return This builder for chaining.
       */
      public Builder setExchangesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        exchanges_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ciphers_ = "";
      /**
       * <code>optional string ciphers = 4;</code>
       * @return Whether the ciphers field is set.
       */
      public boolean hasCiphers() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string ciphers = 4;</code>
       * @return The ciphers.
       */
      public java.lang.String getCiphers() {
        java.lang.Object ref = ciphers_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ciphers_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ciphers = 4;</code>
       * @return The bytes for ciphers.
       */
      public com.google.protobuf.ByteString
          getCiphersBytes() {
        java.lang.Object ref = ciphers_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ciphers_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ciphers = 4;</code>
       * @param value The ciphers to set.
       * @return This builder for chaining.
       */
      public Builder setCiphers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ciphers_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ciphers = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCiphers() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ciphers_ = getDefaultInstance().getCiphers();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ciphers = 4;</code>
       * @param value The bytes for ciphers to set.
       * @return This builder for chaining.
       */
      public Builder setCiphersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ciphers_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hashes_ = "";
      /**
       * <code>optional string hashes = 5;</code>
       * @return Whether the hashes field is set.
       */
      public boolean hasHashes() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string hashes = 5;</code>
       * @return The hashes.
       */
      public java.lang.String getHashes() {
        java.lang.Object ref = hashes_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hashes_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hashes = 5;</code>
       * @return The bytes for hashes.
       */
      public com.google.protobuf.ByteString
          getHashesBytes() {
        java.lang.Object ref = hashes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hashes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hashes = 5;</code>
       * @param value The hashes to set.
       * @return This builder for chaining.
       */
      public Builder setHashes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        hashes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hashes = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHashes() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hashes_ = getDefaultInstance().getHashes();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hashes = 5;</code>
       * @param value The bytes for hashes to set.
       * @return This builder for chaining.
       */
      public Builder setHashesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        hashes_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:spipe.pb.Propose)
    }

    // @@protoc_insertion_point(class_scope:spipe.pb.Propose)
    private static final spipe.pb.Spipe.Propose DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new spipe.pb.Spipe.Propose();
    }

    public static spipe.pb.Spipe.Propose getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Propose>
        PARSER = new com.google.protobuf.AbstractParser<Propose>() {
      @java.lang.Override
      public Propose parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Propose(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Propose> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Propose> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public spipe.pb.Spipe.Propose getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExchangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:spipe.pb.Exchange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes epubkey = 1;</code>
     * @return Whether the epubkey field is set.
     */
    boolean hasEpubkey();
    /**
     * <code>optional bytes epubkey = 1;</code>
     * @return The epubkey.
     */
    com.google.protobuf.ByteString getEpubkey();

    /**
     * <code>optional bytes signature = 2;</code>
     * @return Whether the signature field is set.
     */
    boolean hasSignature();
    /**
     * <code>optional bytes signature = 2;</code>
     * @return The signature.
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code spipe.pb.Exchange}
   */
  public static final class Exchange extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:spipe.pb.Exchange)
      ExchangeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Exchange.newBuilder() to construct.
    private Exchange(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Exchange() {
      epubkey_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Exchange();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Exchange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              epubkey_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              signature_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return spipe.pb.Spipe.internal_static_spipe_pb_Exchange_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return spipe.pb.Spipe.internal_static_spipe_pb_Exchange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              spipe.pb.Spipe.Exchange.class, spipe.pb.Spipe.Exchange.Builder.class);
    }

    private int bitField0_;
    public static final int EPUBKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString epubkey_;
    /**
     * <code>optional bytes epubkey = 1;</code>
     * @return Whether the epubkey field is set.
     */
    @java.lang.Override
    public boolean hasEpubkey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes epubkey = 1;</code>
     * @return The epubkey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEpubkey() {
      return epubkey_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>optional bytes signature = 2;</code>
     * @return Whether the signature field is set.
     */
    @java.lang.Override
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes signature = 2;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, epubkey_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, signature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, epubkey_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof spipe.pb.Spipe.Exchange)) {
        return super.equals(obj);
      }
      spipe.pb.Spipe.Exchange other = (spipe.pb.Spipe.Exchange) obj;

      if (hasEpubkey() != other.hasEpubkey()) return false;
      if (hasEpubkey()) {
        if (!getEpubkey()
            .equals(other.getEpubkey())) return false;
      }
      if (hasSignature() != other.hasSignature()) return false;
      if (hasSignature()) {
        if (!getSignature()
            .equals(other.getSignature())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEpubkey()) {
        hash = (37 * hash) + EPUBKEY_FIELD_NUMBER;
        hash = (53 * hash) + getEpubkey().hashCode();
      }
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static spipe.pb.Spipe.Exchange parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spipe.pb.Spipe.Exchange parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spipe.pb.Spipe.Exchange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spipe.pb.Spipe.Exchange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spipe.pb.Spipe.Exchange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spipe.pb.Spipe.Exchange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spipe.pb.Spipe.Exchange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spipe.pb.Spipe.Exchange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static spipe.pb.Spipe.Exchange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static spipe.pb.Spipe.Exchange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static spipe.pb.Spipe.Exchange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spipe.pb.Spipe.Exchange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(spipe.pb.Spipe.Exchange prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code spipe.pb.Exchange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:spipe.pb.Exchange)
        spipe.pb.Spipe.ExchangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return spipe.pb.Spipe.internal_static_spipe_pb_Exchange_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return spipe.pb.Spipe.internal_static_spipe_pb_Exchange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                spipe.pb.Spipe.Exchange.class, spipe.pb.Spipe.Exchange.Builder.class);
      }

      // Construct using spipe.pb.Spipe.Exchange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        epubkey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        signature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return spipe.pb.Spipe.internal_static_spipe_pb_Exchange_descriptor;
      }

      @java.lang.Override
      public spipe.pb.Spipe.Exchange getDefaultInstanceForType() {
        return spipe.pb.Spipe.Exchange.getDefaultInstance();
      }

      @java.lang.Override
      public spipe.pb.Spipe.Exchange build() {
        spipe.pb.Spipe.Exchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public spipe.pb.Spipe.Exchange buildPartial() {
        spipe.pb.Spipe.Exchange result = new spipe.pb.Spipe.Exchange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.epubkey_ = epubkey_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.signature_ = signature_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof spipe.pb.Spipe.Exchange) {
          return mergeFrom((spipe.pb.Spipe.Exchange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(spipe.pb.Spipe.Exchange other) {
        if (other == spipe.pb.Spipe.Exchange.getDefaultInstance()) return this;
        if (other.hasEpubkey()) {
          setEpubkey(other.getEpubkey());
        }
        if (other.hasSignature()) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        spipe.pb.Spipe.Exchange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (spipe.pb.Spipe.Exchange) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString epubkey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes epubkey = 1;</code>
       * @return Whether the epubkey field is set.
       */
      @java.lang.Override
      public boolean hasEpubkey() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes epubkey = 1;</code>
       * @return The epubkey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEpubkey() {
        return epubkey_;
      }
      /**
       * <code>optional bytes epubkey = 1;</code>
       * @param value The epubkey to set.
       * @return This builder for chaining.
       */
      public Builder setEpubkey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        epubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes epubkey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEpubkey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        epubkey_ = getDefaultInstance().getEpubkey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes signature = 2;</code>
       * @return Whether the signature field is set.
       */
      @java.lang.Override
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes signature = 2;</code>
       * @return The signature.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>optional bytes signature = 2;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes signature = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:spipe.pb.Exchange)
    }

    // @@protoc_insertion_point(class_scope:spipe.pb.Exchange)
    private static final spipe.pb.Spipe.Exchange DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new spipe.pb.Spipe.Exchange();
    }

    public static spipe.pb.Spipe.Exchange getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Exchange>
        PARSER = new com.google.protobuf.AbstractParser<Exchange>() {
      @java.lang.Override
      public Exchange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Exchange(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Exchange> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Exchange> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public spipe.pb.Spipe.Exchange getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NoiseHandshakePayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:spipe.pb.NoiseHandshakePayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes libp2p_key = 1;</code>
     * @return Whether the libp2pKey field is set.
     */
    boolean hasLibp2PKey();
    /**
     * <code>optional bytes libp2p_key = 1;</code>
     * @return The libp2pKey.
     */
    com.google.protobuf.ByteString getLibp2PKey();

    /**
     * <code>optional bytes noise_static_key_signature = 2;</code>
     * @return Whether the noiseStaticKeySignature field is set.
     */
    boolean hasNoiseStaticKeySignature();
    /**
     * <code>optional bytes noise_static_key_signature = 2;</code>
     * @return The noiseStaticKeySignature.
     */
    com.google.protobuf.ByteString getNoiseStaticKeySignature();

    /**
     * <code>optional bytes libp2p_data = 3;</code>
     * @return Whether the libp2pData field is set.
     */
    boolean hasLibp2PData();
    /**
     * <code>optional bytes libp2p_data = 3;</code>
     * @return The libp2pData.
     */
    com.google.protobuf.ByteString getLibp2PData();

    /**
     * <code>optional bytes libp2p_data_signature = 4;</code>
     * @return Whether the libp2pDataSignature field is set.
     */
    boolean hasLibp2PDataSignature();
    /**
     * <code>optional bytes libp2p_data_signature = 4;</code>
     * @return The libp2pDataSignature.
     */
    com.google.protobuf.ByteString getLibp2PDataSignature();
  }
  /**
   * Protobuf type {@code spipe.pb.NoiseHandshakePayload}
   */
  public static final class NoiseHandshakePayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:spipe.pb.NoiseHandshakePayload)
      NoiseHandshakePayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NoiseHandshakePayload.newBuilder() to construct.
    private NoiseHandshakePayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NoiseHandshakePayload() {
      libp2PKey_ = com.google.protobuf.ByteString.EMPTY;
      noiseStaticKeySignature_ = com.google.protobuf.ByteString.EMPTY;
      libp2PData_ = com.google.protobuf.ByteString.EMPTY;
      libp2PDataSignature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NoiseHandshakePayload();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NoiseHandshakePayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              libp2PKey_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              noiseStaticKeySignature_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              libp2PData_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              libp2PDataSignature_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return spipe.pb.Spipe.internal_static_spipe_pb_NoiseHandshakePayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return spipe.pb.Spipe.internal_static_spipe_pb_NoiseHandshakePayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              spipe.pb.Spipe.NoiseHandshakePayload.class, spipe.pb.Spipe.NoiseHandshakePayload.Builder.class);
    }

    private int bitField0_;
    public static final int LIBP2P_KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString libp2PKey_;
    /**
     * <code>optional bytes libp2p_key = 1;</code>
     * @return Whether the libp2pKey field is set.
     */
    @java.lang.Override
    public boolean hasLibp2PKey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes libp2p_key = 1;</code>
     * @return The libp2pKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLibp2PKey() {
      return libp2PKey_;
    }

    public static final int NOISE_STATIC_KEY_SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString noiseStaticKeySignature_;
    /**
     * <code>optional bytes noise_static_key_signature = 2;</code>
     * @return Whether the noiseStaticKeySignature field is set.
     */
    @java.lang.Override
    public boolean hasNoiseStaticKeySignature() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes noise_static_key_signature = 2;</code>
     * @return The noiseStaticKeySignature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNoiseStaticKeySignature() {
      return noiseStaticKeySignature_;
    }

    public static final int LIBP2P_DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString libp2PData_;
    /**
     * <code>optional bytes libp2p_data = 3;</code>
     * @return Whether the libp2pData field is set.
     */
    @java.lang.Override
    public boolean hasLibp2PData() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes libp2p_data = 3;</code>
     * @return The libp2pData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLibp2PData() {
      return libp2PData_;
    }

    public static final int LIBP2P_DATA_SIGNATURE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString libp2PDataSignature_;
    /**
     * <code>optional bytes libp2p_data_signature = 4;</code>
     * @return Whether the libp2pDataSignature field is set.
     */
    @java.lang.Override
    public boolean hasLibp2PDataSignature() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes libp2p_data_signature = 4;</code>
     * @return The libp2pDataSignature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLibp2PDataSignature() {
      return libp2PDataSignature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, libp2PKey_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, noiseStaticKeySignature_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(3, libp2PData_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, libp2PDataSignature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, libp2PKey_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, noiseStaticKeySignature_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, libp2PData_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, libp2PDataSignature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof spipe.pb.Spipe.NoiseHandshakePayload)) {
        return super.equals(obj);
      }
      spipe.pb.Spipe.NoiseHandshakePayload other = (spipe.pb.Spipe.NoiseHandshakePayload) obj;

      if (hasLibp2PKey() != other.hasLibp2PKey()) return false;
      if (hasLibp2PKey()) {
        if (!getLibp2PKey()
            .equals(other.getLibp2PKey())) return false;
      }
      if (hasNoiseStaticKeySignature() != other.hasNoiseStaticKeySignature()) return false;
      if (hasNoiseStaticKeySignature()) {
        if (!getNoiseStaticKeySignature()
            .equals(other.getNoiseStaticKeySignature())) return false;
      }
      if (hasLibp2PData() != other.hasLibp2PData()) return false;
      if (hasLibp2PData()) {
        if (!getLibp2PData()
            .equals(other.getLibp2PData())) return false;
      }
      if (hasLibp2PDataSignature() != other.hasLibp2PDataSignature()) return false;
      if (hasLibp2PDataSignature()) {
        if (!getLibp2PDataSignature()
            .equals(other.getLibp2PDataSignature())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLibp2PKey()) {
        hash = (37 * hash) + LIBP2P_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getLibp2PKey().hashCode();
      }
      if (hasNoiseStaticKeySignature()) {
        hash = (37 * hash) + NOISE_STATIC_KEY_SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getNoiseStaticKeySignature().hashCode();
      }
      if (hasLibp2PData()) {
        hash = (37 * hash) + LIBP2P_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getLibp2PData().hashCode();
      }
      if (hasLibp2PDataSignature()) {
        hash = (37 * hash) + LIBP2P_DATA_SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getLibp2PDataSignature().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static spipe.pb.Spipe.NoiseHandshakePayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spipe.pb.Spipe.NoiseHandshakePayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spipe.pb.Spipe.NoiseHandshakePayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spipe.pb.Spipe.NoiseHandshakePayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spipe.pb.Spipe.NoiseHandshakePayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spipe.pb.Spipe.NoiseHandshakePayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spipe.pb.Spipe.NoiseHandshakePayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spipe.pb.Spipe.NoiseHandshakePayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static spipe.pb.Spipe.NoiseHandshakePayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static spipe.pb.Spipe.NoiseHandshakePayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static spipe.pb.Spipe.NoiseHandshakePayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spipe.pb.Spipe.NoiseHandshakePayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(spipe.pb.Spipe.NoiseHandshakePayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code spipe.pb.NoiseHandshakePayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:spipe.pb.NoiseHandshakePayload)
        spipe.pb.Spipe.NoiseHandshakePayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return spipe.pb.Spipe.internal_static_spipe_pb_NoiseHandshakePayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return spipe.pb.Spipe.internal_static_spipe_pb_NoiseHandshakePayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                spipe.pb.Spipe.NoiseHandshakePayload.class, spipe.pb.Spipe.NoiseHandshakePayload.Builder.class);
      }

      // Construct using spipe.pb.Spipe.NoiseHandshakePayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        libp2PKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        noiseStaticKeySignature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        libp2PData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        libp2PDataSignature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return spipe.pb.Spipe.internal_static_spipe_pb_NoiseHandshakePayload_descriptor;
      }

      @java.lang.Override
      public spipe.pb.Spipe.NoiseHandshakePayload getDefaultInstanceForType() {
        return spipe.pb.Spipe.NoiseHandshakePayload.getDefaultInstance();
      }

      @java.lang.Override
      public spipe.pb.Spipe.NoiseHandshakePayload build() {
        spipe.pb.Spipe.NoiseHandshakePayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public spipe.pb.Spipe.NoiseHandshakePayload buildPartial() {
        spipe.pb.Spipe.NoiseHandshakePayload result = new spipe.pb.Spipe.NoiseHandshakePayload(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.libp2PKey_ = libp2PKey_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.noiseStaticKeySignature_ = noiseStaticKeySignature_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.libp2PData_ = libp2PData_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.libp2PDataSignature_ = libp2PDataSignature_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof spipe.pb.Spipe.NoiseHandshakePayload) {
          return mergeFrom((spipe.pb.Spipe.NoiseHandshakePayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(spipe.pb.Spipe.NoiseHandshakePayload other) {
        if (other == spipe.pb.Spipe.NoiseHandshakePayload.getDefaultInstance()) return this;
        if (other.hasLibp2PKey()) {
          setLibp2PKey(other.getLibp2PKey());
        }
        if (other.hasNoiseStaticKeySignature()) {
          setNoiseStaticKeySignature(other.getNoiseStaticKeySignature());
        }
        if (other.hasLibp2PData()) {
          setLibp2PData(other.getLibp2PData());
        }
        if (other.hasLibp2PDataSignature()) {
          setLibp2PDataSignature(other.getLibp2PDataSignature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        spipe.pb.Spipe.NoiseHandshakePayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (spipe.pb.Spipe.NoiseHandshakePayload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString libp2PKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes libp2p_key = 1;</code>
       * @return Whether the libp2pKey field is set.
       */
      @java.lang.Override
      public boolean hasLibp2PKey() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes libp2p_key = 1;</code>
       * @return The libp2pKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getLibp2PKey() {
        return libp2PKey_;
      }
      /**
       * <code>optional bytes libp2p_key = 1;</code>
       * @param value The libp2pKey to set.
       * @return This builder for chaining.
       */
      public Builder setLibp2PKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        libp2PKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes libp2p_key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLibp2PKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        libp2PKey_ = getDefaultInstance().getLibp2PKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString noiseStaticKeySignature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes noise_static_key_signature = 2;</code>
       * @return Whether the noiseStaticKeySignature field is set.
       */
      @java.lang.Override
      public boolean hasNoiseStaticKeySignature() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes noise_static_key_signature = 2;</code>
       * @return The noiseStaticKeySignature.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getNoiseStaticKeySignature() {
        return noiseStaticKeySignature_;
      }
      /**
       * <code>optional bytes noise_static_key_signature = 2;</code>
       * @param value The noiseStaticKeySignature to set.
       * @return This builder for chaining.
       */
      public Builder setNoiseStaticKeySignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        noiseStaticKeySignature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes noise_static_key_signature = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNoiseStaticKeySignature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        noiseStaticKeySignature_ = getDefaultInstance().getNoiseStaticKeySignature();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString libp2PData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes libp2p_data = 3;</code>
       * @return Whether the libp2pData field is set.
       */
      @java.lang.Override
      public boolean hasLibp2PData() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bytes libp2p_data = 3;</code>
       * @return The libp2pData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getLibp2PData() {
        return libp2PData_;
      }
      /**
       * <code>optional bytes libp2p_data = 3;</code>
       * @param value The libp2pData to set.
       * @return This builder for chaining.
       */
      public Builder setLibp2PData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        libp2PData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes libp2p_data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLibp2PData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        libp2PData_ = getDefaultInstance().getLibp2PData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString libp2PDataSignature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes libp2p_data_signature = 4;</code>
       * @return Whether the libp2pDataSignature field is set.
       */
      @java.lang.Override
      public boolean hasLibp2PDataSignature() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bytes libp2p_data_signature = 4;</code>
       * @return The libp2pDataSignature.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getLibp2PDataSignature() {
        return libp2PDataSignature_;
      }
      /**
       * <code>optional bytes libp2p_data_signature = 4;</code>
       * @param value The libp2pDataSignature to set.
       * @return This builder for chaining.
       */
      public Builder setLibp2PDataSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        libp2PDataSignature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes libp2p_data_signature = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLibp2PDataSignature() {
        bitField0_ = (bitField0_ & ~0x00000008);
        libp2PDataSignature_ = getDefaultInstance().getLibp2PDataSignature();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:spipe.pb.NoiseHandshakePayload)
    }

    // @@protoc_insertion_point(class_scope:spipe.pb.NoiseHandshakePayload)
    private static final spipe.pb.Spipe.NoiseHandshakePayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new spipe.pb.Spipe.NoiseHandshakePayload();
    }

    public static spipe.pb.Spipe.NoiseHandshakePayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NoiseHandshakePayload>
        PARSER = new com.google.protobuf.AbstractParser<NoiseHandshakePayload>() {
      @java.lang.Override
      public NoiseHandshakePayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NoiseHandshakePayload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NoiseHandshakePayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NoiseHandshakePayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public spipe.pb.Spipe.NoiseHandshakePayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spipe_pb_Propose_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spipe_pb_Propose_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spipe_pb_Exchange_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spipe_pb_Exchange_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spipe_pb_NoiseHandshakePayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spipe_pb_NoiseHandshakePayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013spipe.proto\022\010spipe.pb\"[\n\007Propose\022\014\n\004ra" +
      "nd\030\001 \001(\014\022\016\n\006pubkey\030\002 \001(\014\022\021\n\texchanges\030\003 " +
      "\001(\t\022\017\n\007ciphers\030\004 \001(\t\022\016\n\006hashes\030\005 \001(\t\".\n\010" +
      "Exchange\022\017\n\007epubkey\030\001 \001(\014\022\021\n\tsignature\030\002" +
      " \001(\014\"\203\001\n\025NoiseHandshakePayload\022\022\n\nlibp2p" +
      "_key\030\001 \001(\014\022\"\n\032noise_static_key_signature" +
      "\030\002 \001(\014\022\023\n\013libp2p_data\030\003 \001(\014\022\035\n\025libp2p_da" +
      "ta_signature\030\004 \001(\014"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_spipe_pb_Propose_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_spipe_pb_Propose_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spipe_pb_Propose_descriptor,
        new java.lang.String[] { "Rand", "Pubkey", "Exchanges", "Ciphers", "Hashes", });
    internal_static_spipe_pb_Exchange_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_spipe_pb_Exchange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spipe_pb_Exchange_descriptor,
        new java.lang.String[] { "Epubkey", "Signature", });
    internal_static_spipe_pb_NoiseHandshakePayload_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_spipe_pb_NoiseHandshakePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spipe_pb_NoiseHandshakePayload_descriptor,
        new java.lang.String[] { "Libp2PKey", "NoiseStaticKeySignature", "Libp2PData", "Libp2PDataSignature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
