// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unixfs.proto

package io.protos.unixfs;

public final class UnixfsProtos {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_io_protos_unixfs_Data_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_io_protos_unixfs_Data_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_io_protos_unixfs_Metadata_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_io_protos_unixfs_Metadata_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\014unixfs.proto\022\020io.protos.unixfs\"\343\001\n\004Dat" +
                        "a\022-\n\004Type\030\001 \002(\0162\037.io.protos.unixfs.Data." +
                        "DataType\022\014\n\004Data\030\002 \001(\014\022\020\n\010filesize\030\003 \001(\004" +
                        "\022\022\n\nblocksizes\030\004 \003(\004\022\020\n\010hashType\030\005 \001(\004\022\016" +
                        "\n\006fanout\030\006 \001(\004\"V\n\010DataType\022\007\n\003Raw\020\000\022\r\n\tD" +
                        "irectory\020\001\022\010\n\004File\020\002\022\014\n\010Metadata\020\003\022\013\n\007Sy" +
                        "mlink\020\004\022\r\n\tHAMTShard\020\005\"\034\n\010Metadata\022\020\n\010Mi" +
                        "meType\030\001 \001(\tB \n\020io.protos.unixfsB\014Unixfs" +
                        "Protos"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_io_protos_unixfs_Data_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_io_protos_unixfs_Data_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_io_protos_unixfs_Data_descriptor,
                new java.lang.String[]{"Type", "Data", "Filesize", "Blocksizes", "HashType", "Fanout",});
        internal_static_io_protos_unixfs_Metadata_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_io_protos_unixfs_Metadata_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_io_protos_unixfs_Metadata_descriptor,
                new java.lang.String[]{"MimeType",});
    }

    private UnixfsProtos() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    public interface DataOrBuilder extends
            // @@protoc_insertion_point(interface_extends:io.protos.unixfs.Data)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required .io.protos.unixfs.Data.DataType Type = 1;</code>
         *
         * @return Whether the type field is set.
         */
        boolean hasType();

        /**
         * <code>required .io.protos.unixfs.Data.DataType Type = 1;</code>
         *
         * @return The type.
         */
        io.protos.unixfs.UnixfsProtos.Data.DataType getType();

        /**
         * <code>optional bytes Data = 2;</code>
         *
         * @return Whether the data field is set.
         */
        boolean hasData();

        /**
         * <code>optional bytes Data = 2;</code>
         *
         * @return The data.
         */
        com.google.protobuf.ByteString getData();

        /**
         * <code>optional uint64 filesize = 3;</code>
         *
         * @return Whether the filesize field is set.
         */
        boolean hasFilesize();

        /**
         * <code>optional uint64 filesize = 3;</code>
         *
         * @return The filesize.
         */
        long getFilesize();

        /**
         * <code>repeated uint64 blocksizes = 4;</code>
         *
         * @return A list containing the blocksizes.
         */
        java.util.List<java.lang.Long> getBlocksizesList();

        /**
         * <code>repeated uint64 blocksizes = 4;</code>
         *
         * @return The count of blocksizes.
         */
        int getBlocksizesCount();

        /**
         * <code>repeated uint64 blocksizes = 4;</code>
         *
         * @param index The index of the element to return.
         * @return The blocksizes at the given index.
         */
        long getBlocksizes(int index);

        /**
         * <code>optional uint64 hashType = 5;</code>
         *
         * @return Whether the hashType field is set.
         */
        boolean hasHashType();

        /**
         * <code>optional uint64 hashType = 5;</code>
         *
         * @return The hashType.
         */
        long getHashType();

        /**
         * <code>optional uint64 fanout = 6;</code>
         *
         * @return Whether the fanout field is set.
         */
        boolean hasFanout();

        /**
         * <code>optional uint64 fanout = 6;</code>
         *
         * @return The fanout.
         */
        long getFanout();
    }

    public interface MetadataOrBuilder extends
            // @@protoc_insertion_point(interface_extends:io.protos.unixfs.Metadata)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string MimeType = 1;</code>
         *
         * @return Whether the mimeType field is set.
         */
        boolean hasMimeType();

        /**
         * <code>optional string MimeType = 1;</code>
         *
         * @return The mimeType.
         */
        java.lang.String getMimeType();

        /**
         * <code>optional string MimeType = 1;</code>
         *
         * @return The bytes for mimeType.
         */
        com.google.protobuf.ByteString
        getMimeTypeBytes();
    }

    /**
     * Protobuf type {@code io.protos.unixfs.Data}
     */
    public static final class Data extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:io.protos.unixfs.Data)
            DataOrBuilder {
        public static final int TYPE_FIELD_NUMBER = 1;
        public static final int DATA_FIELD_NUMBER = 2;
        public static final int FILESIZE_FIELD_NUMBER = 3;
        public static final int BLOCKSIZES_FIELD_NUMBER = 4;
        public static final int HASHTYPE_FIELD_NUMBER = 5;
        public static final int FANOUT_FIELD_NUMBER = 6;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<Data>
                PARSER = new com.google.protobuf.AbstractParser<Data>() {
            @java.lang.Override
            public Data parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Data(input, extensionRegistry);
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:io.protos.unixfs.Data)
        private static final io.protos.unixfs.UnixfsProtos.Data DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new io.protos.unixfs.UnixfsProtos.Data();
        }

        private int bitField0_;
        private int type_;
        private com.google.protobuf.ByteString data_;
        private long filesize_;
        private com.google.protobuf.Internal.LongList blocksizes_;
        private long hashType_;
        private long fanout_;
        private byte memoizedIsInitialized = -1;

        // Use Data.newBuilder() to construct.
        private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Data() {
            type_ = 0;
            data_ = com.google.protobuf.ByteString.EMPTY;
            blocksizes_ = emptyLongList();
        }

        private Data(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            int rawValue = input.readEnum();
                            @SuppressWarnings("deprecation")
                            io.protos.unixfs.UnixfsProtos.Data.DataType value = io.protos.unixfs.UnixfsProtos.Data.DataType.valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(1, rawValue);
                            } else {
                                bitField0_ |= 0x00000001;
                                type_ = rawValue;
                            }
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            data_ = input.readBytes();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            filesize_ = input.readUInt64();
                            break;
                        }
                        case 32: {
                            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                                blocksizes_ = newLongList();
                                mutable_bitField0_ |= 0x00000008;
                            }
                            blocksizes_.addLong(input.readUInt64());
                            break;
                        }
                        case 34: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000008) != 0) && input.getBytesUntilLimit() > 0) {
                                blocksizes_ = newLongList();
                                mutable_bitField0_ |= 0x00000008;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                blocksizes_.addLong(input.readUInt64());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000008;
                            hashType_ = input.readUInt64();
                            break;
                        }
                        case 48: {
                            bitField0_ |= 0x00000010;
                            fanout_ = input.readUInt64();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000008) != 0)) {
                    blocksizes_.makeImmutable(); // C
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.protos.unixfs.UnixfsProtos.internal_static_io_protos_unixfs_Data_descriptor;
        }

        public static io.protos.unixfs.UnixfsProtos.Data parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.protos.unixfs.UnixfsProtos.Data parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.protos.unixfs.UnixfsProtos.Data parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.protos.unixfs.UnixfsProtos.Data parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.protos.unixfs.UnixfsProtos.Data parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.protos.unixfs.UnixfsProtos.Data parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.protos.unixfs.UnixfsProtos.Data parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.protos.unixfs.UnixfsProtos.Data parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.protos.unixfs.UnixfsProtos.Data parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.protos.unixfs.UnixfsProtos.Data parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.protos.unixfs.UnixfsProtos.Data parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.protos.unixfs.UnixfsProtos.Data parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.protos.unixfs.UnixfsProtos.Data prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static io.protos.unixfs.UnixfsProtos.Data getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Data> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Data();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.protos.unixfs.UnixfsProtos.internal_static_io_protos_unixfs_Data_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.protos.unixfs.UnixfsProtos.Data.class, io.protos.unixfs.UnixfsProtos.Data.Builder.class);
        }

        /**
         * <code>required .io.protos.unixfs.Data.DataType Type = 1;</code>
         *
         * @return Whether the type field is set.
         */
        @java.lang.Override
        public boolean hasType() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required .io.protos.unixfs.Data.DataType Type = 1;</code>
         *
         * @return The type.
         */
        @java.lang.Override
        public io.protos.unixfs.UnixfsProtos.Data.DataType getType() {
            @SuppressWarnings("deprecation")
            io.protos.unixfs.UnixfsProtos.Data.DataType result = io.protos.unixfs.UnixfsProtos.Data.DataType.valueOf(type_);
            return result == null ? io.protos.unixfs.UnixfsProtos.Data.DataType.Raw : result;
        }

        /**
         * <code>optional bytes Data = 2;</code>
         *
         * @return Whether the data field is set.
         */
        @java.lang.Override
        public boolean hasData() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>optional bytes Data = 2;</code>
         *
         * @return The data.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        /**
         * <code>optional uint64 filesize = 3;</code>
         *
         * @return Whether the filesize field is set.
         */
        @java.lang.Override
        public boolean hasFilesize() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>optional uint64 filesize = 3;</code>
         *
         * @return The filesize.
         */
        @java.lang.Override
        public long getFilesize() {
            return filesize_;
        }

        /**
         * <code>repeated uint64 blocksizes = 4;</code>
         *
         * @return A list containing the blocksizes.
         */
        @java.lang.Override
        public java.util.List<java.lang.Long>
        getBlocksizesList() {
            return blocksizes_;
        }

        /**
         * <code>repeated uint64 blocksizes = 4;</code>
         *
         * @return The count of blocksizes.
         */
        public int getBlocksizesCount() {
            return blocksizes_.size();
        }

        /**
         * <code>repeated uint64 blocksizes = 4;</code>
         *
         * @param index The index of the element to return.
         * @return The blocksizes at the given index.
         */
        public long getBlocksizes(int index) {
            return blocksizes_.getLong(index);
        }

        /**
         * <code>optional uint64 hashType = 5;</code>
         *
         * @return Whether the hashType field is set.
         */
        @java.lang.Override
        public boolean hasHashType() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        /**
         * <code>optional uint64 hashType = 5;</code>
         *
         * @return The hashType.
         */
        @java.lang.Override
        public long getHashType() {
            return hashType_;
        }

        /**
         * <code>optional uint64 fanout = 6;</code>
         *
         * @return Whether the fanout field is set.
         */
        @java.lang.Override
        public boolean hasFanout() {
            return ((bitField0_ & 0x00000010) != 0);
        }

        /**
         * <code>optional uint64 fanout = 6;</code>
         *
         * @return The fanout.
         */
        @java.lang.Override
        public long getFanout() {
            return fanout_;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeEnum(1, type_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeBytes(2, data_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                output.writeUInt64(3, filesize_);
            }
            for (int i = 0; i < blocksizes_.size(); i++) {
                output.writeUInt64(4, blocksizes_.getLong(i));
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                output.writeUInt64(5, hashType_);
            }
            if (((bitField0_ & 0x00000010) != 0)) {
                output.writeUInt64(6, fanout_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, type_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, data_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(3, filesize_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < blocksizes_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeUInt64SizeNoTag(blocksizes_.getLong(i));
                }
                size += dataSize;
                size += 1 * getBlocksizesList().size();
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(5, hashType_);
            }
            if (((bitField0_ & 0x00000010) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(6, fanout_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.protos.unixfs.UnixfsProtos.Data)) {
                return super.equals(obj);
            }
            io.protos.unixfs.UnixfsProtos.Data other = (io.protos.unixfs.UnixfsProtos.Data) obj;

            if (hasType() != other.hasType()) return false;
            if (hasType()) {
                if (type_ != other.type_) return false;
            }
            if (hasData() != other.hasData()) return false;
            if (hasData()) {
                if (!getData()
                        .equals(other.getData())) return false;
            }
            if (hasFilesize() != other.hasFilesize()) return false;
            if (hasFilesize()) {
                if (getFilesize()
                        != other.getFilesize()) return false;
            }
            if (!getBlocksizesList()
                    .equals(other.getBlocksizesList())) return false;
            if (hasHashType() != other.hasHashType()) return false;
            if (hasHashType()) {
                if (getHashType()
                        != other.getHashType()) return false;
            }
            if (hasFanout() != other.hasFanout()) return false;
            if (hasFanout()) {
                if (getFanout()
                        != other.getFanout()) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasType()) {
                hash = (37 * hash) + TYPE_FIELD_NUMBER;
                hash = (53 * hash) + type_;
            }
            if (hasData()) {
                hash = (37 * hash) + DATA_FIELD_NUMBER;
                hash = (53 * hash) + getData().hashCode();
            }
            if (hasFilesize()) {
                hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getFilesize());
            }
            if (getBlocksizesCount() > 0) {
                hash = (37 * hash) + BLOCKSIZES_FIELD_NUMBER;
                hash = (53 * hash) + getBlocksizesList().hashCode();
            }
            if (hasHashType()) {
                hash = (37 * hash) + HASHTYPE_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getHashType());
            }
            if (hasFanout()) {
                hash = (37 * hash) + FANOUT_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getFanout());
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Data> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public io.protos.unixfs.UnixfsProtos.Data getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf enum {@code io.protos.unixfs.Data.DataType}
         */
        public enum DataType
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>Raw = 0;</code>
             */
            Raw(0),
            /**
             * <code>Directory = 1;</code>
             */
            Directory(1),
            /**
             * <code>File = 2;</code>
             */
            File(2),
            /**
             * <code>Metadata = 3;</code>
             */
            Metadata(3),
            /**
             * <code>Symlink = 4;</code>
             */
            Symlink(4),
            /**
             * <code>HAMTShard = 5;</code>
             */
            HAMTShard(5),
            ;

            /**
             * <code>Raw = 0;</code>
             */
            public static final int Raw_VALUE = 0;
            /**
             * <code>Directory = 1;</code>
             */
            public static final int Directory_VALUE = 1;
            /**
             * <code>File = 2;</code>
             */
            public static final int File_VALUE = 2;
            /**
             * <code>Metadata = 3;</code>
             */
            public static final int Metadata_VALUE = 3;
            /**
             * <code>Symlink = 4;</code>
             */
            public static final int Symlink_VALUE = 4;
            /**
             * <code>HAMTShard = 5;</code>
             */
            public static final int HAMTShard_VALUE = 5;
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    DataType> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
                        public DataType findValueByNumber(int number) {
                            return DataType.forNumber(number);
                        }
                    };
            private static final DataType[] VALUES = values();
            private final int value;

            private DataType(int value) {
                this.value = value;
            }

            /**
             * @param value The numeric wire value of the corresponding enum entry.
             * @return The enum associated with the given numeric wire value.
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static DataType valueOf(int value) {
                return forNumber(value);
            }

            /**
             * @param value The numeric wire value of the corresponding enum entry.
             * @return The enum associated with the given numeric wire value.
             */
            public static DataType forNumber(int value) {
                switch (value) {
                    case 0:
                        return Raw;
                    case 1:
                        return Directory;
                    case 2:
                        return File;
                    case 3:
                        return Metadata;
                    case 4:
                        return Symlink;
                    case 5:
                        return HAMTShard;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<DataType>
            internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return io.protos.unixfs.UnixfsProtos.Data.getDescriptor().getEnumTypes().get(0);
            }

            public static DataType valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:io.protos.unixfs.Data.DataType)
        }

        /**
         * Protobuf type {@code io.protos.unixfs.Data}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:io.protos.unixfs.Data)
                io.protos.unixfs.UnixfsProtos.DataOrBuilder {
            private int bitField0_;
            private int type_ = 0;
            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
            private long filesize_;
            private com.google.protobuf.Internal.LongList blocksizes_ = emptyLongList();
            private long hashType_;
            private long fanout_;

            // Construct using io.protos.unixfs.UnixfsProtos.Data.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.protos.unixfs.UnixfsProtos.internal_static_io_protos_unixfs_Data_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.protos.unixfs.UnixfsProtos.internal_static_io_protos_unixfs_Data_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.protos.unixfs.UnixfsProtos.Data.class, io.protos.unixfs.UnixfsProtos.Data.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                type_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                data_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000002);
                filesize_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000004);
                blocksizes_ = emptyLongList();
                bitField0_ = (bitField0_ & ~0x00000008);
                hashType_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000010);
                fanout_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000020);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.protos.unixfs.UnixfsProtos.internal_static_io_protos_unixfs_Data_descriptor;
            }

            @java.lang.Override
            public io.protos.unixfs.UnixfsProtos.Data getDefaultInstanceForType() {
                return io.protos.unixfs.UnixfsProtos.Data.getDefaultInstance();
            }

            @java.lang.Override
            public io.protos.unixfs.UnixfsProtos.Data build() {
                io.protos.unixfs.UnixfsProtos.Data result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public io.protos.unixfs.UnixfsProtos.Data buildPartial() {
                io.protos.unixfs.UnixfsProtos.Data result = new io.protos.unixfs.UnixfsProtos.Data(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.type_ = type_;
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.data_ = data_;
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.filesize_ = filesize_;
                    to_bitField0_ |= 0x00000004;
                }
                if (((bitField0_ & 0x00000008) != 0)) {
                    blocksizes_.makeImmutable();
                    bitField0_ = (bitField0_ & ~0x00000008);
                }
                result.blocksizes_ = blocksizes_;
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.hashType_ = hashType_;
                    to_bitField0_ |= 0x00000008;
                }
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    result.fanout_ = fanout_;
                    to_bitField0_ |= 0x00000010;
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.protos.unixfs.UnixfsProtos.Data) {
                    return mergeFrom((io.protos.unixfs.UnixfsProtos.Data) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.protos.unixfs.UnixfsProtos.Data other) {
                if (other == io.protos.unixfs.UnixfsProtos.Data.getDefaultInstance()) return this;
                if (other.hasType()) {
                    setType(other.getType());
                }
                if (other.hasData()) {
                    setData(other.getData());
                }
                if (other.hasFilesize()) {
                    setFilesize(other.getFilesize());
                }
                if (!other.blocksizes_.isEmpty()) {
                    if (blocksizes_.isEmpty()) {
                        blocksizes_ = other.blocksizes_;
                        bitField0_ = (bitField0_ & ~0x00000008);
                    } else {
                        ensureBlocksizesIsMutable();
                        blocksizes_.addAll(other.blocksizes_);
                    }
                    onChanged();
                }
                if (other.hasHashType()) {
                    setHashType(other.getHashType());
                }
                if (other.hasFanout()) {
                    setFanout(other.getFanout());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasType()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.protos.unixfs.UnixfsProtos.Data parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.protos.unixfs.UnixfsProtos.Data) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required .io.protos.unixfs.Data.DataType Type = 1;</code>
             *
             * @return Whether the type field is set.
             */
            @java.lang.Override
            public boolean hasType() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>required .io.protos.unixfs.Data.DataType Type = 1;</code>
             *
             * @return The type.
             */
            @java.lang.Override
            public io.protos.unixfs.UnixfsProtos.Data.DataType getType() {
                @SuppressWarnings("deprecation")
                io.protos.unixfs.UnixfsProtos.Data.DataType result = io.protos.unixfs.UnixfsProtos.Data.DataType.valueOf(type_);
                return result == null ? io.protos.unixfs.UnixfsProtos.Data.DataType.Raw : result;
            }

            /**
             * <code>required .io.protos.unixfs.Data.DataType Type = 1;</code>
             *
             * @param value The type to set.
             * @return This builder for chaining.
             */
            public Builder setType(io.protos.unixfs.UnixfsProtos.Data.DataType value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                type_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>required .io.protos.unixfs.Data.DataType Type = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearType() {
                bitField0_ = (bitField0_ & ~0x00000001);
                type_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes Data = 2;</code>
             *
             * @return Whether the data field is set.
             */
            @java.lang.Override
            public boolean hasData() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>optional bytes Data = 2;</code>
             *
             * @return The data.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getData() {
                return data_;
            }

            /**
             * <code>optional bytes Data = 2;</code>
             *
             * @param value The data to set.
             * @return This builder for chaining.
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                data_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes Data = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearData() {
                bitField0_ = (bitField0_ & ~0x00000002);
                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            /**
             * <code>optional uint64 filesize = 3;</code>
             *
             * @return Whether the filesize field is set.
             */
            @java.lang.Override
            public boolean hasFilesize() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <code>optional uint64 filesize = 3;</code>
             *
             * @return The filesize.
             */
            @java.lang.Override
            public long getFilesize() {
                return filesize_;
            }

            /**
             * <code>optional uint64 filesize = 3;</code>
             *
             * @param value The filesize to set.
             * @return This builder for chaining.
             */
            public Builder setFilesize(long value) {
                bitField0_ |= 0x00000004;
                filesize_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint64 filesize = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearFilesize() {
                bitField0_ = (bitField0_ & ~0x00000004);
                filesize_ = 0L;
                onChanged();
                return this;
            }

            private void ensureBlocksizesIsMutable() {
                if (!((bitField0_ & 0x00000008) != 0)) {
                    blocksizes_ = mutableCopy(blocksizes_);
                    bitField0_ |= 0x00000008;
                }
            }

            /**
             * <code>repeated uint64 blocksizes = 4;</code>
             *
             * @return A list containing the blocksizes.
             */
            public java.util.List<java.lang.Long>
            getBlocksizesList() {
                return ((bitField0_ & 0x00000008) != 0) ?
                        java.util.Collections.unmodifiableList(blocksizes_) : blocksizes_;
            }

            /**
             * <code>repeated uint64 blocksizes = 4;</code>
             *
             * @return The count of blocksizes.
             */
            public int getBlocksizesCount() {
                return blocksizes_.size();
            }

            /**
             * <code>repeated uint64 blocksizes = 4;</code>
             *
             * @param index The index of the element to return.
             * @return The blocksizes at the given index.
             */
            public long getBlocksizes(int index) {
                return blocksizes_.getLong(index);
            }

            /**
             * <code>repeated uint64 blocksizes = 4;</code>
             *
             * @param index The index to set the value at.
             * @param value The blocksizes to set.
             * @return This builder for chaining.
             */
            public Builder setBlocksizes(
                    int index, long value) {
                ensureBlocksizesIsMutable();
                blocksizes_.setLong(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated uint64 blocksizes = 4;</code>
             *
             * @param value The blocksizes to add.
             * @return This builder for chaining.
             */
            public Builder addBlocksizes(long value) {
                ensureBlocksizesIsMutable();
                blocksizes_.addLong(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated uint64 blocksizes = 4;</code>
             *
             * @param values The blocksizes to add.
             * @return This builder for chaining.
             */
            public Builder addAllBlocksizes(
                    java.lang.Iterable<? extends java.lang.Long> values) {
                ensureBlocksizesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, blocksizes_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated uint64 blocksizes = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearBlocksizes() {
                blocksizes_ = emptyLongList();
                bitField0_ = (bitField0_ & ~0x00000008);
                onChanged();
                return this;
            }

            /**
             * <code>optional uint64 hashType = 5;</code>
             *
             * @return Whether the hashType field is set.
             */
            @java.lang.Override
            public boolean hasHashType() {
                return ((bitField0_ & 0x00000010) != 0);
            }

            /**
             * <code>optional uint64 hashType = 5;</code>
             *
             * @return The hashType.
             */
            @java.lang.Override
            public long getHashType() {
                return hashType_;
            }

            /**
             * <code>optional uint64 hashType = 5;</code>
             *
             * @param value The hashType to set.
             * @return This builder for chaining.
             */
            public Builder setHashType(long value) {
                bitField0_ |= 0x00000010;
                hashType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint64 hashType = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearHashType() {
                bitField0_ = (bitField0_ & ~0x00000010);
                hashType_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint64 fanout = 6;</code>
             *
             * @return Whether the fanout field is set.
             */
            @java.lang.Override
            public boolean hasFanout() {
                return ((bitField0_ & 0x00000020) != 0);
            }

            /**
             * <code>optional uint64 fanout = 6;</code>
             *
             * @return The fanout.
             */
            @java.lang.Override
            public long getFanout() {
                return fanout_;
            }

            /**
             * <code>optional uint64 fanout = 6;</code>
             *
             * @param value The fanout to set.
             * @return This builder for chaining.
             */
            public Builder setFanout(long value) {
                bitField0_ |= 0x00000020;
                fanout_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint64 fanout = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearFanout() {
                bitField0_ = (bitField0_ & ~0x00000020);
                fanout_ = 0L;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:io.protos.unixfs.Data)
        }

    }

    /**
     * Protobuf type {@code io.protos.unixfs.Metadata}
     */
    public static final class Metadata extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:io.protos.unixfs.Metadata)
            MetadataOrBuilder {
        public static final int MIMETYPE_FIELD_NUMBER = 1;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<Metadata>
                PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
            @java.lang.Override
            public Metadata parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Metadata(input, extensionRegistry);
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:io.protos.unixfs.Metadata)
        private static final io.protos.unixfs.UnixfsProtos.Metadata DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new io.protos.unixfs.UnixfsProtos.Metadata();
        }

        private int bitField0_;
        private volatile java.lang.Object mimeType_;
        private byte memoizedIsInitialized = -1;

        // Use Metadata.newBuilder() to construct.
        private Metadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Metadata() {
            mimeType_ = "";
        }
        private Metadata(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            mimeType_ = bs;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.protos.unixfs.UnixfsProtos.internal_static_io_protos_unixfs_Metadata_descriptor;
        }

        public static io.protos.unixfs.UnixfsProtos.Metadata parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.protos.unixfs.UnixfsProtos.Metadata parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.protos.unixfs.UnixfsProtos.Metadata parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.protos.unixfs.UnixfsProtos.Metadata parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.protos.unixfs.UnixfsProtos.Metadata parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.protos.unixfs.UnixfsProtos.Metadata parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.protos.unixfs.UnixfsProtos.Metadata parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.protos.unixfs.UnixfsProtos.Metadata parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.protos.unixfs.UnixfsProtos.Metadata parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.protos.unixfs.UnixfsProtos.Metadata parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.protos.unixfs.UnixfsProtos.Metadata parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.protos.unixfs.UnixfsProtos.Metadata parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.protos.unixfs.UnixfsProtos.Metadata prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static io.protos.unixfs.UnixfsProtos.Metadata getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Metadata> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Metadata();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.protos.unixfs.UnixfsProtos.internal_static_io_protos_unixfs_Metadata_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.protos.unixfs.UnixfsProtos.Metadata.class, io.protos.unixfs.UnixfsProtos.Metadata.Builder.class);
        }

        /**
         * <code>optional string MimeType = 1;</code>
         *
         * @return Whether the mimeType field is set.
         */
        @java.lang.Override
        public boolean hasMimeType() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>optional string MimeType = 1;</code>
         *
         * @return The mimeType.
         */
        @java.lang.Override
        public java.lang.String getMimeType() {
            java.lang.Object ref = mimeType_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    mimeType_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string MimeType = 1;</code>
         *
         * @return The bytes for mimeType.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getMimeTypeBytes() {
            java.lang.Object ref = mimeType_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                mimeType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mimeType_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mimeType_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.protos.unixfs.UnixfsProtos.Metadata)) {
                return super.equals(obj);
            }
            io.protos.unixfs.UnixfsProtos.Metadata other = (io.protos.unixfs.UnixfsProtos.Metadata) obj;

            if (hasMimeType() != other.hasMimeType()) return false;
            if (hasMimeType()) {
                if (!getMimeType()
                        .equals(other.getMimeType())) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasMimeType()) {
                hash = (37 * hash) + MIMETYPE_FIELD_NUMBER;
                hash = (53 * hash) + getMimeType().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Metadata> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public io.protos.unixfs.UnixfsProtos.Metadata getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code io.protos.unixfs.Metadata}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:io.protos.unixfs.Metadata)
                io.protos.unixfs.UnixfsProtos.MetadataOrBuilder {
            private int bitField0_;
            private java.lang.Object mimeType_ = "";

            // Construct using io.protos.unixfs.UnixfsProtos.Metadata.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.protos.unixfs.UnixfsProtos.internal_static_io_protos_unixfs_Metadata_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.protos.unixfs.UnixfsProtos.internal_static_io_protos_unixfs_Metadata_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.protos.unixfs.UnixfsProtos.Metadata.class, io.protos.unixfs.UnixfsProtos.Metadata.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                mimeType_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.protos.unixfs.UnixfsProtos.internal_static_io_protos_unixfs_Metadata_descriptor;
            }

            @java.lang.Override
            public io.protos.unixfs.UnixfsProtos.Metadata getDefaultInstanceForType() {
                return io.protos.unixfs.UnixfsProtos.Metadata.getDefaultInstance();
            }

            @java.lang.Override
            public io.protos.unixfs.UnixfsProtos.Metadata build() {
                io.protos.unixfs.UnixfsProtos.Metadata result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public io.protos.unixfs.UnixfsProtos.Metadata buildPartial() {
                io.protos.unixfs.UnixfsProtos.Metadata result = new io.protos.unixfs.UnixfsProtos.Metadata(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.mimeType_ = mimeType_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.protos.unixfs.UnixfsProtos.Metadata) {
                    return mergeFrom((io.protos.unixfs.UnixfsProtos.Metadata) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.protos.unixfs.UnixfsProtos.Metadata other) {
                if (other == io.protos.unixfs.UnixfsProtos.Metadata.getDefaultInstance())
                    return this;
                if (other.hasMimeType()) {
                    bitField0_ |= 0x00000001;
                    mimeType_ = other.mimeType_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.protos.unixfs.UnixfsProtos.Metadata parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.protos.unixfs.UnixfsProtos.Metadata) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional string MimeType = 1;</code>
             *
             * @return Whether the mimeType field is set.
             */
            public boolean hasMimeType() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>optional string MimeType = 1;</code>
             *
             * @return The mimeType.
             */
            public java.lang.String getMimeType() {
                java.lang.Object ref = mimeType_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        mimeType_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string MimeType = 1;</code>
             *
             * @param value The mimeType to set.
             * @return This builder for chaining.
             */
            public Builder setMimeType(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                mimeType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string MimeType = 1;</code>
             *
             * @return The bytes for mimeType.
             */
            public com.google.protobuf.ByteString
            getMimeTypeBytes() {
                java.lang.Object ref = mimeType_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    mimeType_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string MimeType = 1;</code>
             *
             * @param value The bytes for mimeType to set.
             * @return This builder for chaining.
             */
            public Builder setMimeTypeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                mimeType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string MimeType = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMimeType() {
                bitField0_ = (bitField0_ & ~0x00000001);
                mimeType_ = getDefaultInstance().getMimeType();
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:io.protos.unixfs.Metadata)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
