// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plaintext.proto

package plaintext.pb;

public final class Plaintext {
  private Plaintext() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExchangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:plaintext.pb.Exchange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>optional bytes id = 1;</code>
     * @return The id.
     */
    com.google.protobuf.ByteString getId();

    /**
     * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
     * @return Whether the pubkey field is set.
     */
    boolean hasPubkey();
    /**
     * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
     * @return The pubkey.
     */
    crypto.pb.Crypto.PublicKey getPubkey();
    /**
     * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
     */
    crypto.pb.Crypto.PublicKeyOrBuilder getPubkeyOrBuilder();
  }
  /**
   * Protobuf type {@code plaintext.pb.Exchange}
   */
  public static final class Exchange extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:plaintext.pb.Exchange)
      ExchangeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Exchange.newBuilder() to construct.
    private Exchange(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Exchange() {
      id_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Exchange();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Exchange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              crypto.pb.Crypto.PublicKey.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = pubkey_.toBuilder();
              }
              pubkey_ = input.readMessage(crypto.pb.Crypto.PublicKey.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pubkey_);
                pubkey_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return plaintext.pb.Plaintext.internal_static_plaintext_pb_Exchange_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return plaintext.pb.Plaintext.internal_static_plaintext_pb_Exchange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              plaintext.pb.Plaintext.Exchange.class, plaintext.pb.Plaintext.Exchange.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_;
    /**
     * <code>optional bytes id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    public static final int PUBKEY_FIELD_NUMBER = 2;
    private crypto.pb.Crypto.PublicKey pubkey_;
    /**
     * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
     * @return Whether the pubkey field is set.
     */
    @java.lang.Override
    public boolean hasPubkey() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
     * @return The pubkey.
     */
    @java.lang.Override
    public crypto.pb.Crypto.PublicKey getPubkey() {
      return pubkey_ == null ? crypto.pb.Crypto.PublicKey.getDefaultInstance() : pubkey_;
    }
    /**
     * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
     */
    @java.lang.Override
    public crypto.pb.Crypto.PublicKeyOrBuilder getPubkeyOrBuilder() {
      return pubkey_ == null ? crypto.pb.Crypto.PublicKey.getDefaultInstance() : pubkey_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasPubkey()) {
        if (!getPubkey().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getPubkey());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPubkey());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof plaintext.pb.Plaintext.Exchange)) {
        return super.equals(obj);
      }
      plaintext.pb.Plaintext.Exchange other = (plaintext.pb.Plaintext.Exchange) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (!getId()
            .equals(other.getId())) return false;
      }
      if (hasPubkey() != other.hasPubkey()) return false;
      if (hasPubkey()) {
        if (!getPubkey()
            .equals(other.getPubkey())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasPubkey()) {
        hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPubkey().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static plaintext.pb.Plaintext.Exchange parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static plaintext.pb.Plaintext.Exchange parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static plaintext.pb.Plaintext.Exchange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static plaintext.pb.Plaintext.Exchange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static plaintext.pb.Plaintext.Exchange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static plaintext.pb.Plaintext.Exchange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static plaintext.pb.Plaintext.Exchange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static plaintext.pb.Plaintext.Exchange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static plaintext.pb.Plaintext.Exchange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static plaintext.pb.Plaintext.Exchange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static plaintext.pb.Plaintext.Exchange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static plaintext.pb.Plaintext.Exchange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(plaintext.pb.Plaintext.Exchange prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code plaintext.pb.Exchange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:plaintext.pb.Exchange)
        plaintext.pb.Plaintext.ExchangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return plaintext.pb.Plaintext.internal_static_plaintext_pb_Exchange_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return plaintext.pb.Plaintext.internal_static_plaintext_pb_Exchange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                plaintext.pb.Plaintext.Exchange.class, plaintext.pb.Plaintext.Exchange.Builder.class);
      }

      // Construct using plaintext.pb.Plaintext.Exchange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPubkeyFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (pubkeyBuilder_ == null) {
          pubkey_ = null;
        } else {
          pubkeyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return plaintext.pb.Plaintext.internal_static_plaintext_pb_Exchange_descriptor;
      }

      @java.lang.Override
      public plaintext.pb.Plaintext.Exchange getDefaultInstanceForType() {
        return plaintext.pb.Plaintext.Exchange.getDefaultInstance();
      }

      @java.lang.Override
      public plaintext.pb.Plaintext.Exchange build() {
        plaintext.pb.Plaintext.Exchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public plaintext.pb.Plaintext.Exchange buildPartial() {
        plaintext.pb.Plaintext.Exchange result = new plaintext.pb.Plaintext.Exchange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (pubkeyBuilder_ == null) {
            result.pubkey_ = pubkey_;
          } else {
            result.pubkey_ = pubkeyBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof plaintext.pb.Plaintext.Exchange) {
          return mergeFrom((plaintext.pb.Plaintext.Exchange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(plaintext.pb.Plaintext.Exchange other) {
        if (other == plaintext.pb.Plaintext.Exchange.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPubkey()) {
          mergePubkey(other.getPubkey());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasPubkey()) {
          if (!getPubkey().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        plaintext.pb.Plaintext.Exchange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (plaintext.pb.Plaintext.Exchange) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>optional bytes id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      private crypto.pb.Crypto.PublicKey pubkey_;
      private com.google.protobuf.SingleFieldBuilderV3<
          crypto.pb.Crypto.PublicKey, crypto.pb.Crypto.PublicKey.Builder, crypto.pb.Crypto.PublicKeyOrBuilder> pubkeyBuilder_;
      /**
       * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
       * @return Whether the pubkey field is set.
       */
      public boolean hasPubkey() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
       * @return The pubkey.
       */
      public crypto.pb.Crypto.PublicKey getPubkey() {
        if (pubkeyBuilder_ == null) {
          return pubkey_ == null ? crypto.pb.Crypto.PublicKey.getDefaultInstance() : pubkey_;
        } else {
          return pubkeyBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
       */
      public Builder setPubkey(crypto.pb.Crypto.PublicKey value) {
        if (pubkeyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pubkey_ = value;
          onChanged();
        } else {
          pubkeyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
       */
      public Builder setPubkey(
          crypto.pb.Crypto.PublicKey.Builder builderForValue) {
        if (pubkeyBuilder_ == null) {
          pubkey_ = builderForValue.build();
          onChanged();
        } else {
          pubkeyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
       */
      public Builder mergePubkey(crypto.pb.Crypto.PublicKey value) {
        if (pubkeyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              pubkey_ != null &&
              pubkey_ != crypto.pb.Crypto.PublicKey.getDefaultInstance()) {
            pubkey_ =
              crypto.pb.Crypto.PublicKey.newBuilder(pubkey_).mergeFrom(value).buildPartial();
          } else {
            pubkey_ = value;
          }
          onChanged();
        } else {
          pubkeyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
       */
      public Builder clearPubkey() {
        if (pubkeyBuilder_ == null) {
          pubkey_ = null;
          onChanged();
        } else {
          pubkeyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
       */
      public crypto.pb.Crypto.PublicKey.Builder getPubkeyBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPubkeyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
       */
      public crypto.pb.Crypto.PublicKeyOrBuilder getPubkeyOrBuilder() {
        if (pubkeyBuilder_ != null) {
          return pubkeyBuilder_.getMessageOrBuilder();
        } else {
          return pubkey_ == null ?
              crypto.pb.Crypto.PublicKey.getDefaultInstance() : pubkey_;
        }
      }
      /**
       * <code>optional .crypto.pb.PublicKey pubkey = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          crypto.pb.Crypto.PublicKey, crypto.pb.Crypto.PublicKey.Builder, crypto.pb.Crypto.PublicKeyOrBuilder> 
          getPubkeyFieldBuilder() {
        if (pubkeyBuilder_ == null) {
          pubkeyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              crypto.pb.Crypto.PublicKey, crypto.pb.Crypto.PublicKey.Builder, crypto.pb.Crypto.PublicKeyOrBuilder>(
                  getPubkey(),
                  getParentForChildren(),
                  isClean());
          pubkey_ = null;
        }
        return pubkeyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:plaintext.pb.Exchange)
    }

    // @@protoc_insertion_point(class_scope:plaintext.pb.Exchange)
    private static final plaintext.pb.Plaintext.Exchange DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new plaintext.pb.Plaintext.Exchange();
    }

    public static plaintext.pb.Plaintext.Exchange getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Exchange>
        PARSER = new com.google.protobuf.AbstractParser<Exchange>() {
      @java.lang.Override
      public Exchange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Exchange(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Exchange> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Exchange> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public plaintext.pb.Plaintext.Exchange getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_plaintext_pb_Exchange_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_plaintext_pb_Exchange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017plaintext.proto\022\014plaintext.pb\032\014crypto." +
      "proto\"<\n\010Exchange\022\n\n\002id\030\001 \001(\014\022$\n\006pubkey\030" +
      "\002 \001(\0132\024.crypto.pb.PublicKey"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          crypto.pb.Crypto.getDescriptor(),
        });
    internal_static_plaintext_pb_Exchange_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_plaintext_pb_Exchange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_plaintext_pb_Exchange_descriptor,
        new java.lang.String[] { "Id", "Pubkey", });
    crypto.pb.Crypto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
